
const BASE_MAIN_FRONTEND_URL = process.env.REACT_APP_BASE_URL_FRONT
export const BASE_MAIN_FRONTEND_URL_HOME = `${BASE_MAIN_FRONTEND_URL}`
export const BASE_MAIN_FRONTEND_URL_FARMS = `${BASE_MAIN_FRONTEND_URL}/farms`
export const BASE_MAIN_FRONTEND_URL_POOLS = `${BASE_MAIN_FRONTEND_URL}/pools`
